model_dir: weights/ProTrek_650M_UniRef50
#sequence_index_dir: /sujin/Datasets/ProTrek/faiss_index/SwissProt/ProTrek_650M_UniRef50/sequence
sequence_index_dir: /mnt/5t/faiss_index/UniRef50/ProTrek_650M_UniRef50/sequence
structure_index_dir: /sujin/Datasets/ProTrek/faiss_index/SwissProt/ProTrek_650M_UniRef50/structure
text_index_dir: /mnt/5t/faiss_index/UniRef50/ProTrek_650M_UniRef50/text