#model_dir: /sujin/Models/ProTrek/ProTrek_650M_UniRef50
#faiss_config:
#  IO_FLAG_MMAP: True
#sequence_index_dir:
#  - name: UniRef50
#    index_dir: /mnt/33t/sujin/faiss_index/UniRef50/ProTrek_650M_UniRef50/sequence
#  - name: Swiss-Prot
#    index_dir: /sujin/Datasets/ProTrek/faiss_index/SwissProt/ProTrek_650M_UniRef50/sequence
#  - name: PDB
#    index_dir: /sujin/Datasets/ProTrek/faiss_index/PDB/ProTrek_650M_UniRef50/sequence
#  - name: Uncharacterized
#    index_dir: /mnt/33t/sujin/faiss_index/Uncharacterized/ProTrek_650M_UniRef50/sequence
#
#structure_index_dir:
#  - name: Swiss-Prot
#    index_dir: /sujin/Datasets/ProTrek/faiss_index/SwissProt/ProTrek_650M_UniRef50/structure
#  - name: PDB
#    index_dir: /sujin/Datasets/ProTrek/faiss_index/PDB/ProTrek_650M_UniRef50/structure
#
#text_index_dir:
#  - name: UniProt
#    index_dir: /mnt/33t/sujin/faiss_index/UniRef50/ProTrek_650M_UniRef50/text
#  - name: Swiss-Prot
#    index_dir: /sujin/Datasets/ProTrek/faiss_index/SwissProt/ProTrek_650M_UniRef50/text

model_dir: /sujin/Models/ProTrek/ProTrek_650M_UniRef50

faiss_config:
  IO_FLAG_MMAP: True

sequence_index_dir:
  - name: Swiss-Prot
    index_dir: /sujin/Datasets/ProTrek/faiss_index/SwissProt/ProTrek_650M_UniRef50/sequence

  - name: UniRef50
    index_dir: /sujin/Datasets/ProTrek/faiss_index/UniRef50/ProTrek_650M_UniRef50/sequence
    nprobe: 1000

  - name: Uncharacterized
    index_dir: /sujin/Datasets/ProTrek/faiss_index/Uncharacterized/ProTrek_650M_UniRef50/sequence
    nprobe: 1000

  - name: OMG_prot50
    index_dir: /sujin/Datasets/ProTrek/faiss_index/OMG_prot50/ProTrek_650M_UniRef50/sequence
    nprobe: 100

  - name: PDB
    index_dir: /sujin/Datasets/ProTrek/faiss_index/PDB/ProTrek_650M_UniRef50/sequence

structure_index_dir:
  - name: Swiss-Prot
    index_dir: /sujin/Datasets/ProTrek/faiss_index/SwissProt/ProTrek_650M_UniRef50/structure
  - name: PDB
    index_dir: /sujin/Datasets/ProTrek/faiss_index/PDB/ProTrek_650M_UniRef50/structure

text_index_dir:
  - name: UniProt
    index_dir: /sujin/Datasets/ProTrek/faiss_index/UniRef50/ProTrek_650M_UniRef50/text
  - name: Swiss-Prot
    index_dir: /sujin/Datasets/ProTrek/faiss_index/SwissProt/ProTrek_650M_UniRef50/text